issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: nextjs-client
    redirectURIs:
      - http://localhost:3000/api/auth/oauth2/callback/dex
    name: 'Next.js local'
    secret: dev-secret

enablePasswordDB: true

staticPasswords:
  - email: e2e.user@example.test
    # generate new bcyrpt hash: htpasswd -bnBC 10 "" THE_PASSWORD | tr -d ':\n'
    hash: '$2y$10$bogN.exei8vyACcf0QQFzutOahNcKjU1sqxGgdRtYi2Pn/UXNH8ce%'
    username: e2e
    userID: '1001'
